### PR TITLE
Improve native tool name check

### PR DESCRIPTION
**Pull request by collindutter**
- [x] I have read and agree to the contributing guidelines for [submitting new pull requests](https://github.com/griptape-ai/griptape?tab=readme-ov-file#submitting-pull-requests).

## Describe your changes
Validates that Tool name is alphanumeric, and Tool Activity name is alphanumeric with underscores.

### CODE REVIEW

**Comment by collindutter** [comment]
Code cov will probably fail for not checking the activity name branch. This is somewhat non-trivial to test since right now you can't change an Activity's name -- it's set to the function name which is already enforced to be alphanumeric + underscores by python.

**Comment by dylanholmes** [comment]
> Code cov will probably fail for not checking the activity name branch. This is somewhat non-trivial to test since right now you can't change an Activity's name -- it's set to the function name which is already enforced to be alphanumeric + underscores by python.

How about: Mock the class, then have `activity_name()` return something invalid?

**Comment by collindutter** [comment]
@dylanholmes great call, updated.

**Review by dylanholmes — APPROVED** [review]
🙌

**Pull request merged**
