### PR TITLE
adding initial docs for structure as transform

### PR DESCRIPTION
**Pull request by emjay07**
- [ x] I have read and agree to the contributing guidelines for [submitting new pull requests](https://github.com/griptape-ai/griptape?tab=readme-ov-file#submitting-pull-requests).

## Describe your changes
Adding docs for Structure as Transform

## Issue ticket number and link
N/A

----
📚 Documentation preview 📚: https://griptape--1172.org.readthedocs.build//1172/

### CODE REVIEW

**Review by collindutter — COMMENTED** [review]
Can we provide any sort of example of a payload here? Or link to a sample structure?

**Comment by emjay07** [comment]
I can move my Sample structure to the public repo and link that. When you say example Payload, do you mean to create a DC with a Transform?

**Comment by collindutter** [comment]
I just mean including some sort of snippet that explains what this:
> Ensure the Structure you select to run as a Transform is configured to take in a `ListArtifact` as its first positional argument and returns either a `TextArtifact` or `ListArtifact`.

looks like in practice.

**Comment by emjay07** [comment]
Will do -- the Sample will cover that.

**Review by collindutter — APPROVED** [review]

**Pull request merged**
