### PR TITLE
feat: prepend Amazon to bedrock titan embedding

### LINKED ISSUE #372: Rename `BedrockTitanEmbeddingDriver` to `AmazonBedrockTitanEmbeddingDriver`
`BedrockTitanEmbeddingDriver` doesn't follow the naming convention that we use for embedding drivers. It should be renamed to `AmazonBedrockTitanEmbeddingDriver`.

### PR DESCRIPTION
**Pull request by KaushikIyer16**
Closes #372

### CODE REVIEW

**Comment by collindutter** [comment]
Thanks for the PR 🙂

**Comment by KaushikIyer16** [comment]
Hi @collindutter , @vasinov. just pinging you to get an update if I should update the tokenizer with the Amazon prepend as well

**Comment by collindutter** [comment]
Hi @KaushikIyer16, did you see my comment on https://github.com/griptape-ai/griptape/issues/372? Hopefully that gives some direction of where we'd like to go from here. Let me know if you've got any questions and thank you your help!

**Comment by andrewfrench** [comment]
Closing as implemented in #499.

**Pull request closed without merging**
