### PR TITLE
fix griptape-ai/griptape#226

### PR DESCRIPTION
**Pull request by The-Keeper**
- replacing `Union[]` with `|`
- keeping relevant imports

### CODE REVIEW

**Comment by collindutter** [comment]
Thank you for the PR @The-Keeper! Could you please resolve the conflicts on this branch?

**Comment by vasinov** [comment]
@The-Keeper, sorry for taking so long to review this. Could you please resolve the conflicts and then I will merge?

**Review by vasinov — APPROVED** [review]

**Comment by The-Keeper** [comment]
> @The-Keeper, sorry for taking so long to review this. Could you please resolve the conflicts and then I will merge?

Hi. Sorry, screwed up the merge the first time. Should be alright now, please check.

**Review by vasinov — APPROVED** [review]

**Review by collindutter — APPROVED** [review]

**Comment by vasinov** [comment]
@The-Keeper, thanks! Merged.

**Pull request merged**
