### PR TITLE
Updated: BasePromptDriver to publish on a list of EventListner instead of structures

### PR DESCRIPTION
**Pull request by torabshaikh**
This PR fixes this - #643

### CODE REVIEW

**Comment by collindutter** [comment]
Thanks for the PR @torabshaikh! I do think it's a good idea to decouple Prompt Drivers from Structures, but I don't love having to iterate over `EventListener`s in each place we apply this pattern.

Maybe we need an abstraction to hold `EventListener`s? `EventDispatcher`, `EventPublisher`, etc?

**Comment by torabshaikh** [comment]
@collindutter Just to be clear, We need to implement a new class named `EventsMixin` in the `events` module. This class will have a list of `EventListener` and method like `add_event_listener`, `remove_event_listener` and `publish_event`. Does `EventsMixin` needs to iterate over the list and publish on all `event_listener` or it needs to have a single `event_listener`. Do we need to remove all of these three methods from `Structure` or just `publish_event`? Then all of the drivers that right now uses `Structure` to publish event  can use `EventsMixin`  to do that instead.

**Comment by collindutter** [comment]
> We need to implement a new class named EventsMixin in the events module.

Should be added in the `mixins` module, but yes.

> This class will have a list of `EventListener` and method like `add_event_listener`, `remove_event_listener` and `publish_event`.

Yes, good catch I forgot about those other methods.

>  Does EventsMixin needs to iterate over the list and publish on all event_listener or it needs to have a single event_listener

It should iterate over `event_listeners`, just as the methods works in `Structure` today.

> Do we need to remove all of these three methods from Structure or just publish_event?

Yes, remove the methods and field from `Structure`, and add `EventsMixin` to Structure.

> Then all of the drivers that right now uses Structure to publish event can use EventsMixin to do that instead.

Yes.

Finally: [this method](https://github.com/griptape-ai/griptape/blob/add234a75e6ead979b0a018d56c3385c588dcf84/griptape/tasks/prompt_task.py#L67-L72) should change to set `self.prompt_driver.event_listeners` instead of `self.prompt_driver.structure`.

**Comment by collindutter** [comment]
@torabshaikh thanks for starting this work! Some issues in Discord bumped up the urgency of this fix so I am finishing it up here: https://github.com/griptape-ai/griptape/pull/984.

**Pull request closed without merging**
